name: Deploy Backend to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar Dependencias de Producción
        run: |
          cd api
          npm install --production
          cd ..

      - name: Crear Paquete Zip de la API con Node Modules
        run: |
          cd api
          zip -r ../backend.zip .
          cd ..

      - name: Login Oficial en Azure via RBAC Token
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Desplegar en Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'sme-api-master-pablo'
          package: './backend.zip'